---
- name: copy k8s manifest for Prometheus pod monitor
  template:
    src: pod-monitor.yaml.j2
    dest: "{{ k8s_install_dir.path }}/pod-monitor.yaml"

- name: copy k8s manifest for Grafana dashboard
  copy:
    src: "{{ role_path }}/files/grafana-dashboard.yaml"
    dest: "{{ k8s_install_dir.path }}/grafana-dashboard.yaml"

- name: deploy pod monitor and dashboard
  shell: |
    kubectl apply -f {{ k8s_install_dir.path }}/pod-monitor.yaml
    kubectl apply -f {{ k8s_install_dir.path }}/grafana-dashboard.yaml
