---
- name: install Helm chart
  shell: |-
    helm --kubeconfig {{ kubeconfig }} repo add traefik https://helm.traefik.io/traefik
    helm --kubeconfig {{ kubeconfig }} repo update
    helm --kubeconfig {{ kubeconfig }} install --namespace {{ namespace.traefik }} traefik traefik/traefik -f {{ k8s_install_dir.path }}/values.yaml --version {{ helm_chart_version.traefik }}

- name: apply YAML manifests
  shell: |-
    kubectl --kubeconfig {{ kubeconfig }} create -f {{ k8s_install_dir.path }}/middleware.yaml
    kubectl --kubeconfig {{ kubeconfig }} apply -f {{ k8s_install_dir.path }}/ingress.yaml
    kubectl --kubeconfig {{ kubeconfig }} apply -f {{ k8s_install_dir.path }}/service-internal.yaml
