---
- name: install Helm chart
  shell: |-
    helm --kubeconfig {{ kubeconfig }} repo add traefik https://helm.traefik.io/traefik
    helm --kubeconfig {{ kubeconfig }} repo update
    helm --kubeconfig {{ kubeconfig }} install --namespace {{ namespace.traefik }} traefik traefik/traefik -f {{ k8s_install_dir.path }}/values.yaml --version {{ version.traefik }}

- name: deploy ingress-route
  shell: |
    kubectl apply -f {{ k8s_install_dir.path }}/ingress-route.yaml