---
- name: create working directory
  ansible.builtin.tempfile:
    state: directory
    suffix: build
  register: k8s_install_dir

- name: copy k8s manifest for Grafana dashboard
  copy:
    src: "{{ role_path }}/files/ingress-route.yaml"
    dest: "{{ k8s_install_dir.path }}/ingress-route.yaml"

- name: create Helm chart values
  template:
    src: values.yaml.j2
    dest: "{{ k8s_install_dir.path }}/values.yaml"

- name: Check deployment status of Helm chart
  shell: "helm --kubeconfig {{ kubeconfig }} status -n {{ namespace.traefik }} traefik 2>/dev/null | grep 'STATUS: deployed' | awk '{print $2}'"
  ignore_errors: true
  register: helm_chart_status

- include: install.yaml
  when: not helm_chart_status.stdout == "deployed"

- include: upgrade.yaml
  when: helm_chart_status.stdout == "deployed"

- include: monitoring.yaml
  when: monitoring.deploy

- include: debug.yaml

- name: chore
  file:
    path: "{{ k8s_install_dir.path }}"
    state: absent
  when: k8s_install_dir.path is defined
