---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: termine
    tier: backend
  name: termine

spec:
  replicas: 1
  selector:
    matchLabels:
      app: termine
      tier: backend
  template:
    metadata:
      labels:
        app: termine
        tier: backend
    spec:
      initContainers:
        - name: initdb
          image: meetuptalexdev/termine-server:latest
          imagePullPolicy: Always
          command:
            - bash
            - /setup/setup.sh
          envFrom:
            - configMapRef:
                name: termine-env-vars
          volumeMounts:
            - mountPath: /setup
              name: setup
        - name: sqldump
          image: docker.io/bitnami/postgresql:11.11.0-debian-10-r31
          imagePullPolicy: IfNotPresent
          command:
            - bash
            - /setup/load_dump.sh
          env:
            - name: PGPASSWORD
              valueFrom:
                configMapKeyRef:
                  name: termine-env-vars
                  key: DB_PASSWORD
          envFrom:
            - configMapRef:
                name: termine-env-vars
          volumeMounts:
            - mountPath: /sqldumps
              name: adminsql
            - mountPath: /setup
              name: loaddump
        - name: preset
          image: meetuptalexdev/termine-server:latest
          imagePullPolicy: Always
          command:
            - bash
            - /setup/preset.sh
          envFrom:
            - configMapRef:
                name: termine-env-vars
          volumeMounts:
            - mountPath: /setup
              name: preset
      containers:
        - name: termine
          image: meetuptalexdev/termine-server:latest
          imagePullPolicy: Always
          command:
            - bash
            - /setup/entrypoint.sh
          envFrom:
            - configMapRef:
                name: termine-env-vars
            - configMapRef:
                name: termine-ldap-vars
          ports:
            - containerPort: 8000
              hostPort: 8000
              name: http
          volumeMounts:
            - mountPath: /setup
              name: entrypoint
      restartPolicy: Always
      volumes:
        - name: setup
          configMap:
            name: scripts
            items:
              - key: setup.sh
                path: setup.sh
        - name: entrypoint
          configMap:
            name: scripts
            items:
              - key: entrypoint.sh
                path: entrypoint.sh
        - name: loaddump
          configMap:
            name: scripts
            items:
              - key: load_dump.sh
                path: load_dump.sh
        - name: adminsql
          configMap:
            name: scripts
            items:
              - key: admin.psql
                path: admin.psql
        - name: preset
          configMap:
            name: scripts
            items:
              - key: preset.sh
                path: preset.sh

---
apiVersion: v1
kind: Service
metadata:
  name: termine-service

spec:
  selector:
    app: termine
    tier: backend
  type: ClusterIP
  ports:
    - port: 8000
      name: http
      protocol: TCP
