# Variables defined here will be set by Ansible during runtime

variable "outputs_dir" {
  type = string
  description = "Directory to store outputs files generated by Terraform"
  default = "env"
}

variable "hcloud_token" {
  type = string
  description = "Hetzner Cloud API Token"
}
variable "dns_token" {
  type = string
  description = "Hetzner DNS Console Token"
}

variable "datacenter" {
  type = string
  description = "Location of the Hetzner datacenter"
}

variable "network_zone" {
  type = string
  description = "Network zone - eu-central includes: hel1, fsn1, nbg1"
  default = "eu-central"
}

variable "master_server_type" {
  type = string
  description = "Master server type"
}

variable "worker_server_type" {
  type = string
  description = "Worker server type"
}

variable "master_count" {
  type = number
  description = "Master server count"
}

variable "worker_count" {
  type = number
  description = "Worker server count"
}

variable "use_single_master" {
  type = number
  description = "Switch to enable single master setup"
  default = 1
}

variable "os_image" {
  type = string
  description = "Image of operating system for servers"
}

variable "cluster_name" {
  type = string
  description = "Name for this Kubernetes cluster"
}

variable "network_name" {
  type = string
  description = "Name for the private network"
}

variable "network_ip_range" {
  type = string
  description = "Private network IP range"
}

variable "subnet_master_ip_range" {
  type = string
  description = "Private subnet IP range for master nodes"
}

variable "subnet_master_ip" {
  type = string
  description = "Private subnet IP prefix for master nodes"
}

variable "subnet_worker_ip_range" {
  type = string
  description = "Private subnet IP range for worker nodes"
}

variable "subnet_worker_ip" {
  type = string
  description = "Private subnet IP prefix for worker nodes"
}

variable "subnet_all_offset" {
  type = number
  description = "Offset for IP addresses, all node types"
  default = 1
}

variable "domain" {
  type = string
  description = "Top level domain"
}

variable "subdomain" {
  type = string
  description = "Subdomain e.g. for cluster service hostnames"
  default = "k8s"
}

variable "control_plane_host" {
  type = string
  description = "Name of the control plane host"
  default = "api"
}

variable "traefik_dashboard_host" {
  type = string
  description = "Name of the Traefik dashboard host"
  default = "ingress"
}

variable "application_host" {
  type = string
  description = "Name of the Application host"
  default = "brauche.impftermine"
}

variable "dns_ttl" {
  type = string
  description = "Time to live for a freshly created DNS record"
  default = "300"
}

variable "ssh_key" {
  type = string
  description = "Your SSH key for server access"
}
