---
- name: add hostnames to /etc/hosts
  vars:
    comment: '# added by ansible'
  lineinfile:
    dest: /etc/hosts
    regexp: "brauche.impftermine.neotokyo.space.minikube"
    line: "{{ minikube_ip }} brauche.impftermine.neotokyo.space.minikube {{ comment }}"
    state: present
    backup: no
