---
- name: deploy Prometheus Operator and Grafana
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - "env/config.yaml"
    - "env/namespace.yaml"
    - "env/version.yaml"
  roles:
    - { role: prometheus-operator, tags: prometheus-operator }
  pre_tasks:
    - name: create k8s namespace
      shell: |
        kubectl --kubeconfig {{ kubeconfig }} create namespace {{ namespace.monitoring }} || true
