---
- name: create deployment
  copy:
    src: "{{ role_path }}/files/deployment.yaml"
    dest: "{{ k8s_install_dir.path }}/deployment.yaml"

- name: create config map
  template:
    src: configmap.yaml.j2
    dest: "{{ k8s_install_dir.path }}/configmap.yaml"

- name: deploy k8s manifests
  shell: |-
    kubectl --kubeconfig {{ kubeconfig }} apply -f {{ k8s_install_dir.path }}/
