---
- name: deploy 389DS LDAP server
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - "env/config.yaml"
    - "env/namespace.yaml"
    - "env/version.yaml"
  roles:
    - { role: ldap, tags: ldap }
  pre_tasks:
    - name: create k8s namespace
      shell: |
        kubectl --kubeconfig {{ kubeconfig }} create namespace {{ namespace.ldap }} || true
