---
- name: deploy Traefik as ingress controller
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - "env/config.yaml"
    - "env/namespace.yaml"
    - "env/version.yaml"
  roles:
    - { role: traefik, tags: traefik }
  pre_tasks:
    - name: create k8s namespace
      shell: |
        kubectl --kubeconfig {{ kubeconfig }} create namespace {{ namespace.traefik }} || true
