---
- name: create deployment
  copy:
    src: "{{ role_path }}/files/deployment.yaml"
    dest: "{{ k8s_install_dir.path }}/deployment.yaml"

- name: create config map
  template:
    src: configmap.yaml.j2
    dest: "{{ k8s_install_dir.path }}/configmap.yaml"

- name: deploy k8s manifests
  shell: |-
    kubectl --kubeconfig {{ kubeconfig }} apply -f {{ k8s_install_dir.path }}/

- name: wait for pods become created
  shell: "kubectl get pod --selector app=termine --output=jsonpath='{.items[*].metadata.name}'"
  register: pods_created
  until: item in pods_created.stdout
  retries: 20
  delay: 15
  with_items:
    - termine

- name: wait for pods become ready
  shell: "kubectl wait --for=condition=Ready pods --selector app=termine --timeout=600s"
  register: pods_ready
