---
- name: deploy Postgres SQL database
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - "env/setup.yaml"
    - "env/app.yaml"
  vars:
    kubeconfig: "{{ kube_dir }}/{{ kube_config }}"
  roles:
    - { role: postgres, tags: postgres }
  pre_tasks:
    - name: install Ansible module dependencies
      pip:
        name: openshift
        state: present
    - name: "create k8s namespace - {{ namespace.postgres }}"
      community.kubernetes.k8s:
        kubeconfig: "{{ kubeconfig }}"
        name: "{{ namespace.postgres }}"
        api_version: v1
        kind: Namespace
        state: present
