---
- name: create service account
  template:
    src: serviceaccount.yaml.j2
    dest: "{{ k8s_install_dir.path }}/serviceaccount.yaml"

- name: create stateful set
  template:
    src: statefulset.yaml.j2
    dest: "{{ k8s_install_dir.path }}/statefulset.yaml"

- name: create service
  template:
    src: service.yaml.j2
    dest: "{{ k8s_install_dir.path }}/service.yaml"

- name: deploy k8s manifests
  shell: |-
    kubectl --kubeconfig {{ kubeconfig }} create -f {{ k8s_install_dir.path }}/
